componentName: shipping
appPort: 8080
appVersion: 3.0.1
externalSecret:
  enabled: true
resources:
   limits:
     cpu: 1000m
     memory: 3500Mi
   requests:
     cpu: 1000m
     memory: 3500Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
healthEndpoint: /health
